Repository invertase/react-native-firebase, pull requests merged in 2020-11, with the labels that each got.

#4520 feat(crashlytics ios): put input files when pod install.
  packages/crashlytics/react-native.config.js
Labels: Blocked: Missing CLA, Workflow: Needs Review

#4439 feat(firestore): add toJSON() and valueOf() to FirestoreTimestamp
  packages/firestore/lib/FirestoreTimestamp.js
Labels: Workflow: Pending Merge

#3775 fix(storage): Changed refFromUrl regex to exclude appspot.com
  packages/storage/e2e/StorageTask.e2e.js
  packages/storage/e2e/storage.e2e.js
  packages/storage/lib/utils.js
  tests/e2e/mocha.opts
Labels: Workflow: Pending Merge

#4531 fix(firestore): add missing MIN_SECONDS constant to FirestoreTimestamp
  packages/firestore/lib/FirestoreTimestamp.js
  packages/firestore/lib/index.d.ts
Labels: Service: Firestore, Workflow: Needs Review

#4533 feat(app, ios): bump firebase-ios-sdk to 7.1.0 from 7.0.0
  packages/app/RNFBApp.podspec
  packages/app/package.json
  tests/ios/Podfile
  tests/ios/Podfile.lock
Labels: Workflow: Pending Merge

#4565 feat(admob, ios): add adaptive banner support
  packages/admob/ios/RNFBAdMob/RNFBAdMobCommon.m
  packages/admob/lib/BannerAdSize.js
  packages/admob/lib/index.d.ts
Labels: Service: AdMob, Type: New Feature, Workflow: Waiting for User Response

#4597 fix(app, android): remove firebase-core from dependencies
  packages/app/android/build.gradle
Labels: Platform: Android

#4536 fix(analytics): added missing quantity parameter to the Item structure
  packages/analytics/android/src/reactnative/java/io/invertase/firebase/analytics/ReactNativeFirebaseAnalyticsModule.java
  packages/analytics/e2e/analytics.e2e.js
  packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m
  packages/analytics/lib/index.d.ts
  packages/analytics/lib/structs.js
Labels: Workflow: Needs Review

#4560 fix(ios, badge): use new JSON location for FCM badge information
  packages/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.m
Labels: Help: iOS, Impact: Bug, Platform: iOS, Service: Messaging, Type: Bug Fix, Type: Firebase, Workflow: Needs Review

#4609 feat(crashlytics): add custom message ability to javascript stack traces
  packages/crashlytics/e2e/crashlytics.e2e.js
  packages/crashlytics/lib/handlers.js
  packages/crashlytics/lib/index.d.ts
  packages/crashlytics/lib/index.js
Labels: Workflow: Needs Review, Workflow: Pending Merge

#4618 chore: make ReactNativeFirebaseMessagingSerializer + events builder functions public
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java
Labels: Workflow: Pending Merge

#4619 fix(app): convert NativeFirebaseError.getStackWithMessage to static to fix crash
  packages/app/lib/internal/NativeFirebaseError.js
  packages/functions/lib/HttpsError.js
Labels: Workflow: Pending Merge
