Repository invertase/react-native-firebase, pull requests merged in 2020-10, with the labels that each got.

#3455 fix(storage): bug when getting the root ref of a bucket
  packages/storage/ios/RNFBStorage/RNFBStorageModule.m
Labels: Platform: iOS, Resolution: Needs Repro, Service: Storage

#4304 feat(ios, messaging): add getIsHeadless method to access iOS launch state
  docs/messaging/usage/index.md
  packages/messaging/ios/RNFBMessaging/RNFBMessaging+NSNotificationCenter.h
  packages/messaging/ios/RNFBMessaging/RNFBMessaging+NSNotificationCenter.m
  packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
  packages/messaging/lib/index.d.ts
  packages/messaging/lib/index.js
Labels: Workflow: Pending Merge

#4346 docs(ml-vision): text-recognition accepts only image file types :fire:
  docs/ml-vision/text-recognition.md
Labels: Workflow: Pending Merge

#4133 test(firestore): simplify firestore tests
  .github/workflows/scripts/firebase.json
  .github/workflows/scripts/firestore.indexes.json
  .github/workflows/scripts/firestore.rules
  CONTRIBUTING.md
  packages/app/e2e/config.e2e.js
  packages/firestore/e2e/CollectionReference/add.e2e.js
  packages/firestore/e2e/CollectionReference/doc.e2e.js
  packages/firestore/e2e/CollectionReference/properties.e2e.js
  packages/firestore/e2e/DocumentChange.e2e.js
  packages/firestore/e2e/DocumentReference/collection.e2e.js
  packages/firestore/e2e/DocumentReference/delete.e2e.js
  packages/firestore/e2e/DocumentReference/get.e2e.js
  packages/firestore/e2e/DocumentReference/isEqual.e2e.js
  packages/firestore/e2e/DocumentReference/onSnapshot.e2e.js
  packages/firestore/e2e/DocumentReference/properties.e2e.js
  packages/firestore/e2e/DocumentReference/set.e2e.js
  packages/firestore/e2e/DocumentReference/update.e2e.js
  packages/firestore/e2e/DocumentSnapshot/data.e2e.js
  packages/firestore/e2e/DocumentSnapshot/get.e2e.js
  packages/firestore/e2e/DocumentSnapshot/isEqual.e2e.js
  packages/firestore/e2e/DocumentSnapshot/properties.e2e.js
  packages/firestore/e2e/FieldPath.e2e.js
  packages/firestore/e2e/FieldValue.e2e.js
  packages/firestore/e2e/GeoPoint.e2e.js
  packages/firestore/e2e/Query/endAt.e2e.js
  packages/firestore/e2e/Query/endBefore.e2e.js
  packages/firestore/e2e/Query/get.e2e.js
  packages/firestore/e2e/Query/isEqual.e2e.js
  packages/firestore/e2e/Query/limit.e2e.js
  packages/firestore/e2e/Query/limitToLast.e2e.js
  packages/firestore/e2e/Query/onSnapshot.e2e.js
  packages/firestore/e2e/Query/orderBy.e2e.js
  packages/firestore/e2e/Query/query.e2e.js
  packages/firestore/e2e/Query/startAfter.e2e.js
  packages/firestore/e2e/Query/startAt.e2e.js
  packages/firestore/e2e/Query/where.e2e.js
  packages/firestore/e2e/QuerySnapshot.e2e.js
  packages/firestore/e2e/SnapshotMetadata.e2e.js
  packages/firestore/e2e/Transaction.e2e.js
  packages/firestore/e2e/WriteBatch/commit.e2e.js
  packages/firestore/e2e/WriteBatch/delete.e2e.js
  packages/firestore/e2e/WriteBatch/set.e2e.js
  packages/firestore/e2e/WriteBatch/update.e2e.js
  packages/firestore/e2e/firestore.e2e.js
  packages/firestore/e2e/helpers.js
  packages/firestore/e2e/issues.e2e.js
  tests/e2e/mocha.opts
  tests/ios/Podfile.lock
  tests/ios/testing.xcodeproj/project.pbxproj
Labels: Workflow: Pending Merge

#4401 chore(sdks, tests): update SDKs / Fix tests compile for xcode12
  .github/workflows/tests_e2e.yml
  docs/index.md
  package.json
  packages/app/package.json
  packages/ml-vision/android/build.gradle
  tests/README.md
  tests/ios/Podfile
  tests/ios/Podfile.lock
  tests/ios/testing.xcodeproj/project.pbxproj
  tests/package.json
Labels: Workflow: Needs Second Review, Workflow: Pending Merge

#4412 docs: update manual link URLs in migrating-to-v6.md
  docs/migrating-to-v6.md
Labels: Blocked: Missing CLA, Workflow: Pending Merge

#4455 fix(docs, messaging): tools schema declaration required for notification color override
  docs/messaging/usage/index.md
Labels: Blocked: Missing CLA, Workflow: Waiting for User Response
