Repository invertase/react-native-firebase, pull requests merged in 2020-12, with the labels that each got.

#4634 fix(messaging): get remote message from messaging store on new intent
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
Labels: Workflow: Pending Merge

#4640 test(Podfile): use firestore-ios-framework version vs master
  tests/ios/Podfile
Labels: Tools: CI, Type: Testing, Workflow: Pending Merge

#4652 docs(firebasejson config): missing docs for FirebaseJsonConfig
  .spellcheck.dict.txt
  docs/app/json-config.md
  docs/app/usage.md
  docs/app/utils.md
  docs/sidebar.yaml
  packages/admob/lib/index.d.ts
  packages/analytics/lib/index.d.ts
  packages/app/firebase-schema.json
  packages/app/lib/index.d.ts
  packages/crashlytics/lib/index.d.ts
  packages/database/lib/index.d.ts
  packages/in-app-messaging/lib/index.d.ts
  packages/messaging/lib/index.d.ts
  packages/perf/lib/index.d.ts
  website/gatsby-browser.js
  website/gatsby-node.js
  website/scripts/create-documentation-pages.js
  website/scripts/parse-mdx.js
  website/scripts/source-jsonconfig.js
  website/src/styles.css
  website/src/templates/json-config.tsx
  website/src/types/json-config.ts
Labels: Workflow: Pending Merge

#4676 fix(ios, storage): handle nil file extension from ios14 M1 emulators
  packages/storage/ios/RNFBStorage/RNFBStorageCommon.m
Labels: Workflow: Pending Merge

#4688 fix(storage, ios): resolve listAll promise once and only once on error
  packages/storage/e2e/StorageReference.e2e.js
  packages/storage/ios/RNFBStorage/RNFBStorageModule.m
Labels: Impact: Crash, Platform: iOS, Service: Storage, Type: Bug Fix
