Repository invertase/react-native-firebase, pull requests merged in 2020-09, with the labels that each got.

#4201 feat(inappmessaging): add support for triggering custom events
  packages/in-app-messaging/android/src/main/java/io/invertase/firebase/fiam/UniversalFirebaseFiamModule.java
  packages/in-app-messaging/android/src/reactnative/java/io/invertase/firebase/fiam/ReactNativeFirebaseFiamModule.java
  packages/in-app-messaging/e2e/fiam.e2e.js
  packages/in-app-messaging/ios/RNFBFiam/RNFBFiamModule.m
  packages/in-app-messaging/lib/index.d.ts
  packages/in-app-messaging/lib/index.js
Labels: Service: In-App Messaging, Type: New Feature

#4179 fix: Add missing null to profile update
  packages/auth/lib/index.d.ts
Labels: Service: Authentication, Type: Bug Fix, Workflow: Pending Merge

#3810 feat(firestore, types): support Generic Types
  packages/firestore/lib/index.d.ts
Labels: Workflow: Pending Merge

#4250 docs(analytics): analytics() methods are async
  docs/analytics/usage/index.md
Labels: Blocked: Missing CLA, Workflow: Pending Merge

#4312 docs(types, dynamic-links): ShortLinkType is accessible via statics
  packages/dynamic-links/lib/index.d.ts
Labels: Service: Links, Tools: Typings, Type: Docs

#4306 fix(types): enable TypeScript libCheck & resolve type conflicts
  package.json
  packages/admob/__tests__/admob.test.ts
  packages/admob/lib/index.d.ts
  packages/analytics/lib/index.d.ts
  packages/app/lib/index.d.ts
  packages/auth/lib/index.d.ts
  packages/crashlytics/lib/index.d.ts
  packages/database/lib/index.d.ts
  packages/dynamic-links/lib/index.d.ts
  packages/firestore/lib/index.d.ts
  packages/functions/lib/index.d.ts
  packages/iid/lib/index.d.ts
  packages/in-app-messaging/lib/index.d.ts
  packages/messaging/lib/index.d.ts
  packages/ml-natural-language/lib/index.d.ts
  packages/ml-vision/lib/BarcodeDetectorTypes.d.ts
  packages/ml-vision/lib/index.d.ts
  packages/ml-vision/type-test.ts
  packages/perf/lib/index.d.ts
  packages/remote-config/lib/index.d.ts
  packages/storage/lib/index.d.ts
  scripts/_TEMPLATE_/lib/index.d.ts
  tsconfig.json
  website/package.json
  website/scripts/generate-typedoc.js
Labels: Tools: Typings, Type: Bug Fix, Workflow: Needs Review

#4317 fix(android, messaging): store notifications in prefs ring buffer for initial/open attribution
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/JsonConvert.java
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingReceiver.java
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStore.java
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreHelper.java
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreImpl.java
Labels: Workflow: Needs Review
