Repository invertase/react-native-firebase, pull requests merged in 2021-08, with the labels that each got.

#5565 fix(expo): Do not publish plugin tests and sources to NPM
  packages/app/.npmignore
  packages/crashlytics/.npmignore
  packages/perf/.npmignore
Labels: Workflow: Pending Merge

#5587 test(e2e, android): avoid database emulator on android
  tests/app.js
Labels: Workflow: Pending Merge

#5595 build(deps): firebase emulator 9.16.4 fixes auth token issues
  tests/package.json
  yarn.lock
Labels: Workflow: Pending Merge

#5598 fix(app, android): put app init provider / registrar in correct manifest
  packages/app/android/src/main/AndroidManifest.xml
  packages/app/android/src/reactnative/AndroidManifest.xml
Labels: Workflow: Pending Merge

#5593 feat(dynamic-links): add support for utmParameters
  packages/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java
  packages/dynamic-links/e2e/dynamicLinks.e2e.js
  packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksAppDelegateInterceptor.h
  packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksAppDelegateInterceptor.m
  packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksModule.m
  packages/dynamic-links/lib/index.d.ts
Labels: Workflow: Waiting for User Response, Workflow: Pending Merge

#5618 docs(analytics): fix incorrect docs appearing on reference page
  packages/analytics/lib/index.d.ts
Labels: Type: Docs, Workflow: Pending Merge

#5625 docs(messaging): a little typo fix
  docs/messaging/server-integration.md
Labels: Blocked: Missing CLA, Workflow: Pending Merge

#5667 fix(app-distribution, ios): avoid crash when releaseNotes is nil
  packages/app-distribution/ios/RNFBAppDistribution/RNFBAppDistributionModule.m
Labels: Workflow: Pending Merge

#5662 fix(dynamic-links, android): check for null currentIntent in getInitialLink to avoid crash
  packages/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java
Labels: Workflow: Pending Merge

#5668 fix(app-distribution, ios): missing downloadURL
  packages/app-distribution/ios/RNFBAppDistribution/RNFBAppDistributionModule.m
Labels: Workflow: Pending Merge

#5669 docs(app-distribution): AppDistributionRelease.releaseNotes marked as nullable
  packages/app-distribution/lib/index.d.ts
Labels: Workflow: Pending Merge
