Repository invertase/react-native-firebase, pull requests merged in 2021-02, with the labels that each got.

#4855 feat(app): firebase-ios-sdk 7.4.0 -> 7.5.0, firebase-android-sdk 26.30 -> 26.4.0
  packages/app/package.json
  tests/ios/Podfile
  tests/ios/Podfile.lock
Labels: Workflow: Pending Merge

#4849 fix(admob): improve defense logic to prevent multiple calls
  packages/admob/lib/ads/InterstitialAd.js
  packages/admob/lib/ads/MobileAd.js
  packages/admob/lib/ads/RewardedAd.js
Labels: Blocked: Missing CLA, Service: AdMob, Workflow: Pending Merge

#4886 fix(auth, android): do not timezone offset when getting UTC timestamp
  packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java
  packages/auth/e2e/user.e2e.js
Labels: Platform: Android, Service: Authentication, Workflow: Waiting for User Response

#4894 fix(dynamic-links, dependencies): analytics is optional
  packages/dynamic-links/package.json
Labels: Workflow: Pending Merge

#4909 fix(dynamic-links, ios): remove double-reject on resolveLink
  packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksModule.m
Labels: Workflow: Pending Merge

#4912 docs(FAQ): add info re: disabling debugger for test crashes under Xcode
  .spellcheck.dict.txt
  docs/faqs-and-tips.md
Labels: Workflow: Pending Merge

#4928 docs(common): Improve paragraph readability
  website/package.json
  website/src/components/Mdx.tsx
  website/src/styles.css
Labels: Blocked: Missing CLA, Workflow: Needs Review

#4920 fix(admob): AdEventHandler returns javascript (not native) unsubscribe function
  packages/admob/lib/ads/MobileAd.js
Labels: Workflow: Needs Review

#4952 chore(docs): Updated VsCode debugging instructions
  tests/README.md
Labels: Workflow: Pending Merge
