Repository invertase/react-native-firebase, pull requests merged in 2021-04, with the labels that each got.

#5117 fix(crashlytics, debug): Disable Crashlytics in debug mode by default
  packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsInitProvider.java
  packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m
Labels: Workflow: Needs Review

#5126 fix(app, ios): formally note cocoapods v1.10+ requirement in podspec
  packages/app/RNFBApp.podspec
Labels: Workflow: Pending Merge

#5139 test(iOS): avoid intermittent leveldb duplicate symbol build failure
  tests/ios/Podfile
  tests/ios/Podfile.lock
Labels: Workflow: Pending Merge

#5141 fix(database, types): harmonize database.on() w/firebase-js-sdk
  packages/database/lib/index.d.ts
Labels: Workflow: Pending Merge

#5118 fix(android, utils): fix rare crash getting documents directory
  packages/app/android/src/reactnative/java/io/invertase/firebase/utils/ReactNativeFirebaseUtilsModule.java
  packages/app/lib/index.d.ts
Labels: Workflow: Pending Merge, Workflow: Waiting for User Response

#5153 fix(app, ios-plist): make sure Info.plist exists before processing
  packages/app/react-native.config.js
Labels: Workflow: Pending Merge

#5177 test(workflows): update workflow actions
  .github/workflows/create_test_patches.yml
  .github/workflows/docs.yml
  .github/workflows/linting.yml
  .github/workflows/tests_e2e.yml
  .github/workflows/tests_jest.yml
Labels: Workflow: Pending Merge

#5178 test(detox): remove trace level logging
  .github/workflows/tests_e2e.yml
  package.json
Labels: Workflow: Pending Merge

#5181 fix(messaging): Missing notification on restart
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStore.java
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreImpl.java
Labels: Workflow: Pending Merge

#5210 feat(analytics): add method to retrieve the app instance id from the …
  docs/analytics/usage/index.md
  packages/analytics/android/src/main/java/io/invertase/firebase/analytics/UniversalFirebaseAnalyticsModule.java
  packages/analytics/android/src/reactnative/java/io/invertase/firebase/analytics/ReactNativeFirebaseAnalyticsModule.java
  packages/analytics/e2e/analytics.e2e.js
  packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m
  packages/analytics/lib/index.d.ts
  packages/analytics/lib/index.js
Labels: Workflow: Pending Merge

#5220 fix(database, update): allow empty objects in ref.update()
  packages/database/e2e/reference/update.e2e.js
  packages/database/lib/DatabaseReference.js
Labels: Workflow: Pending Merge

#5229 fix(analytics): import using package name not relative path
  packages/analytics/lib/index.js
Labels: Workflow: Pending Merge

#5232 fix(analytics): added missing price parameter to the Item structure
  packages/analytics/e2e/analytics.e2e.js
  packages/analytics/lib/index.d.ts
  packages/analytics/lib/structs.js
Labels: Platform: JavaScript, Service: Analytics, Type: New Feature, Workflow: Pending Merge

#5236 fix(messaging, android): repair crash handling remote notifications
  packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
Labels: Workflow: Pending Merge

#5235 feat(app, android): support list of Activities to ignore when detecting AppState
  packages/app/android/src/reactnative/java/io/invertase/firebase/common/ReactNativeFirebaseJSON.java
  packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java
  packages/app/firebase-schema.json
  tests/firebase.json
Labels: Workflow: Pending Merge
