Repository invertase/react-native-firebase, pull requests merged in 2021-11, with the labels that each got.

#5827 docs(expo): emphasize important instructions in Expo set up
  docs/index.md
Labels: Workflow: Waiting for User Response, Workflow: Pending Merge

#5852 feat(android, emulator): add firebase.json config element to bypass localhost remap
  jest.setup.ts
  packages/app/firebase-schema.json
  packages/auth/lib/index.js
  packages/firestore/lib/index.js
  packages/functions/lib/index.js
  tests/firebase.json
Labels: Blocked: Missing CLA, Workflow: Pending Merge

#5887 docs(database, offline): setPersistence* methods are sync not async
  docs/database/offline-support.md
  packages/database/lib/index.d.ts
Labels: Workflow: Pending Merge
