Repository invertase/react-native-firebase, pull requests merged in 2023-01, with the labels that each got.

#6857 docs(functions): replace deprecated 'faker' with '@faker-js/faker'
  docs/functions/writing-deploying-functions.md
Labels: Type: Docs, Service: Functions, Workflow: Pending Merge

#6858 docs(functions): replace deprecated 'useFunctionsEmulator' with 'useEmulator'
  docs/functions/usage/index.md
Labels: Workflow: Pending Merge

#6782 fix(database,typescript): transaction update types
  packages/database/lib/index.d.ts
Labels: Service: Database, Tools: Typings, Type: Bug Fix, Workflow: Pending Merge

#6574 feat(auth): Add support for OpenID Connect provider
  .spellcheck.dict.txt
  docs/auth/multi-factor-auth.md
  docs/auth/oidc-auth.md
  docs/auth/phone-auth.md
  docs/sidebar.yaml
  packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
  packages/auth/e2e/provider.e2e.js
  packages/auth/ios/RNFBAuth/RNFBAuthModule.m
  packages/auth/lib/index.js
  packages/auth/lib/providers/OIDCAuthProvider.js
Labels: Workflow: Pending Merge

#6588 feat(perf): add custom screen rendering traces for android
  docs/perf/usage/index.md
  packages/perf/android/src/main/java/io/invertase/firebase/perf/ScreenTrace.java
  packages/perf/android/src/main/java/io/invertase/firebase/perf/UniversalFirebasePerfModule.java
  packages/perf/android/src/reactnative/java/io/invertase/firebase/perf/ReactNativeFirebasePerfModule.java
  packages/perf/e2e/perf.e2e.js
  packages/perf/lib/ScreenTrace.js
  packages/perf/lib/index.d.ts
  packages/perf/lib/index.js
  tests/ios/Podfile.lock
Labels: Workflow: Pending Merge, hacktoberfest-accepted
