Repository invertase/react-native-firebase, pull requests merged in 2024-01, with the labels that each got.

#7439 docs(messaging): update notification example for react-navigation v6
  docs/messaging/notifications.md
Labels: Blocked: Missing CLA, Workflow: Pending Merge

#7541 fix(auth, ios): factorId nil check
  packages/auth/ios/RNFBAuth/RNFBAuthModule.m
Labels: Workflow: Pending Merge

#7543 fix(firestore): increase amount of maximum disjunctions in firebase
  packages/firestore/e2e/Query/where.and.filter.e2e.js
  packages/firestore/e2e/Query/where.e2e.js
  packages/firestore/e2e/Query/where.filter.e2e.js
  packages/firestore/e2e/Query/where.or.filter.e2e.js
  packages/firestore/lib/FirestoreQuery.js
Labels: Workflow: Pending Merge

#7570 fix: typing for firestore `orderBy`
  packages/firestore/lib/index.d.ts
Labels: Workflow: Pending Merge

#7552 fix: tests:packager:jet-reset-cache 'Cannot find module' - issue/7551
  package.json
Labels: Workflow: Pending Merge

#7569 docs(auth, mfa): fix example code typo
  docs/auth/multi-factor-auth.md
Labels: Workflow: Pending Merge

#7564 fix(auth): use correct app instance (vs always default) in multifactor and phone auth
  packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
  packages/auth/ios/RNFBAuth/RNFBAuthModule.m
  packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
Labels: Service: Authentication, Workflow: Pending Merge

#7600 docs(app, expo): updating app.json related to useFrameworks
  docs/index.md
Labels: Type: Docs, Platform: Expo, Blocked: Missing CLA, Workflow: Pending Merge
