Repository invertase/react-native-firebase, pull requests merged in 2024-05, with the labels that each got.

#7760 feat(analytics): allow custom event parameters for begin_checkout and purchase events
  packages/analytics/__tests__/analytics.test.ts
  packages/analytics/lib/index.d.ts
  packages/analytics/lib/structs.js
Labels: Workflow: Pending Merge

#7762 feat(functions): typescript definitions for httpsCallable and httpsCallableFromUrl
  packages/functions/lib/index.d.ts
Labels: Workflow: Pending Merge

#7777 feat(functions): typescript definitions for modular functions API
  packages/functions/lib/modular/index.d.ts
  packages/functions/lib/modular/index.js
Labels: Workflow: Needs Review

#7792 build(ci): fix patch set generation to handle modern react-native / yarn
  .github/workflows/create_test_patches.yml
Labels: Workflow: Pending Merge

#7793 fix(auth, android): return credential for signin if phone auth has link collision
  packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
Labels: Workflow: Needs Review

#7688 fix(app): react-native 0.74 bridgeless mode compatibility
  packages/app/lib/internal/registry/nativeModule.js
Labels: Workflow: Waiting for User Response, Type: React Native, Workflow: Pending Merge
