Repository invertase/react-native-firebase, pull requests merged in 2025-04, with the labels that each got.

#8366 fix(app): annotate initializeApp return as a promise
  packages/app/lib/modular/index.d.ts
Labels: type: bug, tools: typings

#8438 fix(app): firebase-ios-sdk 11.11.0 / firebase-android-sdk 33.12.0
  docs/index.md
  packages/app/package.json
  tests/ios/Podfile.lock
Labels: Workflow: Pending Merge

#8471 chore: example test app for users to run. Initialised VertexAi example
  package.json
  tests/test-app/README.md
  tests/test-app/examples/vertexai.js
  tests/test-app/index.js
  tests/test-app/metro.config.js
Labels: Workflow: Pending Merge

#8478 chore(auth): fix typo in Expo plugin error message
  packages/auth/plugin/src/ios/urlTypes.ts
Labels: Workflow: Pending Merge

#8450 feat(auth)!: use native for isSignInWithEmailLink / BREAKING CHANGE: return type now `Promise<boolean>` not `boolean`
  packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
  packages/auth/e2e/emailLink.e2e.js
  packages/auth/ios/RNFBAuth/RNFBAuthModule.m
  packages/auth/lib/index.d.ts
  packages/auth/lib/index.js
  packages/auth/lib/modular/index.d.ts
  packages/auth/lib/modular/index.js
  packages/auth/lib/web/RNFBAuthModule.js
Labels: Workflow: Pending Merge

#8483 fix(firestore)!: Make DocumentSnapshot.exists() a method rather than a property (BREAKING CHANGE)
  packages/firestore/e2e/CollectionReference/add.e2e.js
  packages/firestore/e2e/DocumentReference/delete.e2e.js
  packages/firestore/e2e/DocumentSnapshot/properties.e2e.js
  packages/firestore/e2e/SecondDatabase/second.Transation.e2e.js
  packages/firestore/e2e/Transaction.e2e.js
  packages/firestore/e2e/WriteBatch/commit.e2e.js
  packages/firestore/lib/FirestoreDocumentSnapshot.js
  packages/firestore/lib/FirestoreQuery.js
Labels: blocked: do-not-merge
