Repository invertase/react-native-firebase, pull requests merged in 2025-02, with the labels that each got.

#8259 fix(firestore, ios): account for filters in getAggregateFromServer with collection groups
  packages/firestore/e2e/Aggregate/AggregateQuery.e2e.js
  packages/firestore/ios/RNFBFirestore/RNFBFirestoreCollectionModule.m
  tests/ios/Podfile.lock
Labels: Needs Attention

#8250 chore: Update Invertase logo
  README.md
  packages/analytics/README.md
  packages/app-check/README.md
  packages/app-distribution/README.md
  packages/app/README.md
  packages/auth/README.md
  packages/crashlytics/README.md
  packages/database/README.md
  packages/dynamic-links/README.md
  packages/firestore/README.md
  packages/functions/README.md
  packages/in-app-messaging/README.md
  packages/installations/README.md
  packages/messaging/README.md
  packages/ml/README.md
  packages/perf/README.md
  packages/remote-config/README.md
  packages/storage/README.md
  scripts/_TEMPLATE_/README.md
  tests/README.md
  website/src/components/Footer.tsx
Labels: Needs Attention

#8279 docs: deprecation guide for moving to firebase-js-sdk modular API
  .spellcheck.dict.txt
  docs/index.md
  docs/migrating-to-v22.md
  docs/sidebar.yaml
  docs/typescript.md
  packages/app/lib/common/index.js
Labels: Needs Attention

#8304 fix: the init calls for modular should use modular getApp()
  packages/analytics/lib/modular/index.js
  packages/app-check/lib/modular/index.js
  packages/app-distribution/lib/modular/index.js
  packages/auth/lib/modular/index.js
  packages/crashlytics/lib/modular/index.js
  packages/database/lib/modular/index.js
  packages/dynamic-links/lib/modular/index.js
  packages/firestore/__tests__/firestore.test.ts
  packages/firestore/lib/modular/index.js
  packages/functions/lib/modular/index.js
  packages/in-app-messaging/lib/modular/index.js
  packages/installations/lib/modular/index.js
  packages/messaging/lib/modular/index.js
  packages/ml/lib/modular/index.js
  packages/perf/lib/modular/index.js
  packages/remote-config/lib/modular/index.js
  packages/storage/lib/modular/index.js
Labels: Needs Attention

#8305 docs(app, expo): add note about uninstalling Expo Go as needed
  docs/index.md
Labels: plugin: app-core, platform: expo, Workflow: Pending Merge, type: documentation

#8274 feat(remote-config): support for custom signals
  packages/remote-config/__tests__/remote-config.test.ts
  packages/remote-config/android/src/main/java/io/invertase/firebase/config/UniversalFirebaseConfigModule.java
  packages/remote-config/android/src/reactnative/java/io/invertase/firebase/config/ReactNativeFirebaseConfigModule.java
  packages/remote-config/e2e/config.e2e.js
  packages/remote-config/ios/RNFBConfig/RNFBConfigModule.m
  packages/remote-config/lib/modular/index.d.ts
  packages/remote-config/lib/modular/index.js
  packages/remote-config/lib/web/RNFBConfigModule.js
Labels: plugin: remote_config, type: enhancement

#8324 feat(app): Support AppDelegate.swift in @react-native-firebase/app on Expo
  packages/app/plugin/__tests__/__snapshots__/iosPlugin.test.ts.snap
  packages/app/plugin/__tests__/fixtures/AppDelegate_sdk45.swift
  packages/app/plugin/__tests__/iosPlugin.test.ts
  packages/app/plugin/src/ios/appDelegate.ts
Labels: Workflow: Pending Merge

#8128 feat(messaging, ios): Background Completion Handler from JS
  packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.h
  packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
  packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
  packages/messaging/lib/index.js
Labels: platform: ios, Workflow: Waiting for User Response, plugin: messaging, type: enhancement, Workflow: Pending Merge, Needs Attention

#8321 fix(remote-config): ensure static objects are exposed for modular API
  packages/remote-config/__tests__/remote-config.test.ts
  packages/remote-config/lib/index.js
  packages/remote-config/lib/modular/index.d.ts
  packages/remote-config/lib/modular/index.js
  packages/remote-config/lib/statics.js
Labels: Workflow: Pending Merge

#8318 fix(messaging): 3 statics not correctly exported
  packages/messaging/__tests__/messaging.test.ts
  packages/messaging/lib/index.js
  packages/messaging/lib/modular/index.d.ts
  packages/messaging/lib/modular/index.js
  packages/messaging/lib/statics.js
Labels: Workflow: Pending Merge

#8322 fix(storage): expose static types for modular API
  packages/storage/__tests__/storage.test.ts
  packages/storage/lib/StorageReference.js
  packages/storage/lib/StorageStatics.js
  packages/storage/lib/StorageTask.js
  packages/storage/lib/index.js
  packages/storage/lib/modular/index.d.ts
  packages/storage/lib/modular/index.js
Labels: Needs Attention

#8343 build(deps): react-native 0.77.1 + all other javascript deps
  .github/workflows/scripts/functions/package.json
  .github/workflows/scripts/functions/yarn.lock
  package.json
  packages/app-check/package.json
  packages/app-distribution/package.json
  packages/app/package.json
  packages/auth/package.json
  packages/crashlytics/package.json
  packages/dynamic-links/package.json
  packages/messaging/package.json
  packages/perf/package.json
  tests/ios/Podfile.lock
  tests/package.json
  tests/patches/detox+20.34.0.patch
  tests/patches/react-native+0.77.0.patch
  yarn.lock
Labels: Workflow: Pending Merge

#8345 fix(firestore, bytes): return Bytes for modular API usage, fix deprecation
  packages/firestore/e2e/Bytes.e2e.js
  packages/firestore/e2e/DocumentSnapshot/data.e2e.js
  packages/firestore/lib/FirestoreBlob.js
  packages/firestore/lib/modular/Bytes.d.ts
  packages/firestore/lib/modular/Bytes.js
  packages/firestore/lib/utils/serialize.js
Labels: plugin: firestore, Workflow: Pending Merge

#8354 fix(crashlytics): convert internal API usage to modular
  packages/crashlytics/lib/handlers.js
Labels: Workflow: Pending Merge
