Repository invertase/react-native-firebase, pull requests merged in 2025-03, with the labels that each got.

#8384 docs(remote-config, ios): remove android-only marker on setConfigSettings
  packages/remote-config/lib/modular/index.js
Labels: plugin: remote_config, Workflow: Pending Merge, type: documentation

#8404 fix(firestore): use correct key to cache instance
  packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.m
Labels: platform: ios, plugin: firestore

#8410 fix(ios): adopt firebase-ios-sdk 11.10.0
  docs/index.md
  packages/app/package.json
  tests/ios/Podfile.lock
Labels: platform: ios

#8415 fix(android): adopt firebase-android-sdk 33.11.0
  docs/index.md
  packages/app-distribution/android/build.gradle
  packages/app/package.json
Labels: platform: android, Workflow: Pending Merge

#8265 docs: Add instructions for iOS AppDelegate.swift on react-native 0.77
  docs/index.md
Labels: Workflow: Pending Merge

#8323 fix(auth): Fix auth type definitions and add more
  packages/auth/__tests__/auth.test.ts
  packages/auth/lib/modular/index.d.ts
  packages/auth/lib/modular/index.js
  packages/auth/type-test.ts
Labels: Workflow: Pending Merge

#8420 docs(app): install doc preening
  docs/index.md
Labels: Workflow: Needs Review

#8425 docs(tips-n-tricks): update new arch to note no current problems
  .spellcheck.dict.txt
  docs/faqs-and-tips.md
Labels: Needs Attention

#8426 docs(app-check): update `initializeApp` example to include proper params
  docs/app-check/usage/index.md
Labels: Workflow: Pending Merge, plugin: app-check, type: documentation

#8421 test: tighten rules-unit-testing patch, matches upstream PR attempt
  tests/patches/@firebase+rules-unit-testing+4.0.1.patch
Labels: Workflow: Pending Merge

#8431 docs(app, expo): clarify note about handling previous Expo dev builds
  docs/index.md
Labels: Workflow: Pending Merge

#8436 fix(auth): fix faulty AuthListenerCallback import
  packages/auth/lib/modular/index.d.ts
  packages/auth/type-test.ts
Labels: Workflow: Pending Merge
