Repository invertase/react-native-firebase, pull requests merged in 2025-01, with the labels that each got.

#8203 fix(auth, iOS): Expo plugin: skip expo-router for auth URLs
  packages/auth/plugin/__tests__/__snapshots__/iosPlugin_openUrlFix.test.ts.snap
  packages/auth/plugin/__tests__/__snapshots__/iosPlugin_urlTypes.test.ts.snap
  packages/auth/plugin/__tests__/fixtures/AppDelegate_bare_sdk43.m
  packages/auth/plugin/__tests__/fixtures/AppDelegate_fallback.m
  packages/auth/plugin/__tests__/fixtures/AppDelegate_sdk42.m
  packages/auth/plugin/__tests__/fixtures/AppDelegate_sdk44.m
  packages/auth/plugin/__tests__/fixtures/AppDelegate_sdk45.mm
  packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts
  packages/auth/plugin/__tests__/iosPlugin_urlTypes.test.ts
  packages/auth/plugin/src/index.ts
  packages/auth/plugin/src/ios/index.ts
  packages/auth/plugin/src/ios/openUrlFix.ts
  packages/auth/plugin/src/ios/urlTypes.ts
  packages/auth/plugin/src/pluginConfig.ts
Labels: Workflow: Pending Merge

#8238 fix(analytics,web): sets no-cors on analytics requests for web
  packages/analytics/lib/web/api.js
Labels: Needs Attention

#8226 Fix code example for Google Social Auth in docs.
  docs/auth/social-auth.md
Labels: Workflow: Pending Merge

#8243 docs(analytics): note possible problems with event parameters
  docs/analytics/usage/index.md
  docs/dynamic-links/usage/index.md
Labels: plugin: analytics, Workflow: Pending Merge
