Repository invertase/react-native-firebase, pull requests merged in 2025-05, with the labels that each got.

#8507 fix(auth, expo): lowercase `String?` in swift using `.lowercased()`
  packages/auth/plugin/__tests__/__snapshots__/iosPlugin_openUrlFix.test.ts.snap
  packages/auth/plugin/src/ios/openUrlFix.ts
Labels: Workflow: Waiting for User Response, Workflow: Pending Merge, Needs Attention

#8327 docs(auth): update examples to use modular API
  docs/auth/multi-factor-auth.md
  docs/auth/oidc-auth.md
  docs/auth/phone-auth.md
  docs/auth/social-auth.md
  docs/auth/usage/index.md
Labels: plugin: authentication, impact: web-implementation, Workflow: Pending Merge, Needs Attention

#8518 docs(auth): clarify fetchSignInMethodsForEmail behavior with email enumeration protection
  packages/auth/lib/index.d.ts
Labels: plugin: authentication, Workflow: Pending Merge

#8519 docs(auth): clarify signInWithEmailAndPassword error behavior under email enumeration protection
  packages/auth/lib/index.d.ts
Labels: plugin: authentication, Workflow: Pending Merge, Needs Attention

#8521 feat(app-check): add Swift AppDelegate support for Expo SDK53+
  packages/app-check/plugin/__tests__/fixtures/AppDelegate_sdk53.swift
  packages/app-check/plugin/__tests__/iosPlugin.test.ts
  packages/app-check/plugin/src/ios/appDelegate.ts
Labels: platform: ios, platform: expo, Workflow: Pending Merge, plugin: app-check

#8529 fix(app-check, types): modular exports of ReactNativeFirebaseAppCheckProvider types
  packages/app-check/__tests__/appcheck.test.ts
  packages/app-check/lib/modular/index.d.ts
Labels: Workflow: Pending Merge

#8530 fix(storage): add missing type for StringFormat object values
  packages/storage/lib/modular/index.d.ts
Labels: plugin: storage, Workflow: Pending Merge

#8517 fix(auth, ios): fixes inappropriate linking when host is nil
  packages/auth/plugin/__tests__/__snapshots__/iosPlugin_openUrlFix.test.ts.snap
  packages/auth/plugin/src/ios/openUrlFix.ts
Labels: platform: ios, plugin: authentication, platform: expo, Blocked: Missing CLA, Workflow: Pending Merge, Needs Attention
