Repository invertase/react-native-firebase, pull requests merged in 2025-06, with the labels that each got.

#8549 fix(app): firebase-android-sdk 33.14.0 / firebase-ios-sdk 11.13.0
  docs/index.md
  packages/app/package.json
  tests/ios/Podfile.lock
Labels: Needs Attention

#8197 chore(analytics): deprecation warnings for v8 API ahead of future major release
  packages/analytics/__tests__/analytics.test.ts
  packages/analytics/e2e/analytics.e2e.js
  packages/analytics/lib/modular/index.js
  packages/app/lib/common/index.js
Labels: Needs Attention

#8569 fix(docs): add a necessary await operator to the example code for initializeAppCheck()
  docs/app-check/usage/index.md
Labels: Workflow: Pending Merge

#8565 docs(authentication): updated sign in with 2FA docs with the correct …
  docs/auth/multi-factor-auth.md
Labels: Blocked: Missing CLA, Workflow: Pending Merge, Needs Attention
